services:
  database:
    container_name: ${APP_NAME}-container-database
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
